PleasPlan/OMO-project

OMO-project/src/components/Search/Search.jsx, OMO-project/src/components/Search/Search.module.css
=> [markup] 메인페이지 검색창 마크업 최종

OMO-project/src/App.jsx, OMO-project/src/components/Header/Header.jsx, OMO-project/src/components/Search/Search.jsx, OMO-project/src/const/main.js, OMO-project/src/const/sub.js
컴포넌트 및 페이지에 이미지 파일 이름 영문으로 바꾼거 맞춰서 코드 수정함
=> [chore] 이미지 이름 변경한 것으로 코드 수정

OMO-project/src/App.jsx, OMO-project/src/components/Search/Search.module.css, OMO-project/src/const/eating.js, OMO-project/src/const/playing.js, OMO-project/src/const/themeCafe.js, OMO-project/src/const/watching.js, OMO-project/src/pages/sub/eating/Eating.jsx, OMO-project/src/pages/sub/playing/Playing.jsx, OMO-project/src/pages/sub/theme-cafe/ThemeCafe.jsx, OMO-project/src/pages/sub/watching/Watching.jsx
- 먹거리 페이지
- 볼거리 페이지
- 놀거리 페이지
- 테마카페 페이지
=> [style] 소분류 페이지 컴포넌트 완성 및 배치

OMO-project/src/App.jsx, OMO-project/src/pages/main/Main.jsx
Main.jsx에서 헤더와 검색창 컴포넌트 삭제 (헤더와 검색창은 App.jsx에서 불러오게끔 했음)
=> [chore] Main.jsx 수정

OMO-project/src/App.jsx, OMO-project/src/components/CategoryBox/CategoryBox.jsx, OMO-project/src/pages/signup/Signup.jsx, OMO-project/src/pages/signup/Signup.module.css
- 회원가입 페이지 부분 마크업
- 화살표 함수로 일부수정
- 컴포넌트 표기 수정
=> Fe 회원가입 페이지 부분 마크업 및 일부 수정

OMO-project/src/components/CategoryBox/CategoryBox.jsx, OMO-project/src/components/CategoryBox/CategoryBox.module.css, OMO-project/src/components/Search/Search.module.css
- 글자 그림자 추가
- hover 시 카테고리 박스 그림자 추가
=> [style] hover 시 그림자 추가

OMO-project/src/components/DetailItems/DetailItems.jsx, OMO-project/src/components/DetailItems/DetailItems.module.css, OMO-project/src/components/DetailItems/Review/Review.jsx, OMO-project/src/const/data.js, OMO-project/src/const/review.js, OMO-project/src/pages/detail/Detail.jsx, OMO-project/src/utils/priceTemplate.js
상세페이지 마크업
- 메뉴에 리스트 추가 및 불러오기
- 리뷰 데이터 생성 및 불러오기
- 가격 템플릿 생성
=> [Fe] 상세페이지 마크업 (메뉴 리스트 추가 및 리뷰 데이터 불러오기)

OMO-project/src/const/communityFreePost.js, OMO-project/src/const/communityWorryPost.js, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx
CommunityPost →CommunityWorryPost
=> [Fe] CommunityWorryPost 파일 경로 이름 변경

OMO-project/src/App.jsx, OMO-project/src/const/communityFreePost.js, OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx
=> [Fe] 커뮤니티 자유게시판 페이지 마크업 구현

OMO-project/src/App.jsx, OMO-project/src/components/Header/Header.jsx, OMO-project/src/components/Mypage/Mypage.jsx, OMO-project/src/components/MypageListBox/MypageListBox.jsx, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx
- 내정보왼쪽카테고리 (개별 페이지로 이동)
- 리스트들->상세페이지
- 회원탈퇴 버튼->메인페이지
=> Fe: route 경로 설정

OMO-project/src/components/CommunityPost/CommunityPost.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/DetailItems/DetailItemsNone/DetailItemsNone.jsx, OMO-project/src/components/DetailItems/DetailItemsTariff/DetailItemsTariff.jsx, OMO-project/src/components/ListBox/ListBox.jsx, OMO-project/src/components/MyCourse/MyCourseDataBox/MyCourseDataBox.jsx, OMO-project/src/components/ReportModal/ReportModal.jsx, OMO-project/src/components/ReportModal/ReportModal.module.css, OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.module.css, OMO-project/src/utils/Portal.jsx, OMO-project/src/utils/Time/elapsedText.js
- 커뮤니티 페이지 좋아요 색, 리뷰 개수, input창 비우기 기능 추가 
- 상세페이지 리뷰 개수 기능 추가 
- 기타 레이아웃 수정
=> [Fe] 커뮤니티, 상세페이지 기능 추가 

OMO-project/src/components/CommunityPost/CommunityPost.jsx, OMO-project/src/components/MyCourse/MyCourseCalendar/MyCourseCalendar.jsx, OMO-project/src/components/MyCourse/MyCourseSearchBox/FindButton/FindButton.jsx, OMO-project/src/components/MyCourse/MyCourseSearchBox/FindButton/FindButton.module.css, OMO-project/src/components/MyCourse/MyCourseSearchBox/MyCourseSearchBox.jsx, OMO-project/src/components/MyCourse/MyCourseSearchBox/MyCourseSearchBox.module.css, OMO-project/src/components/ReportModal/ReportModal.jsx, OMO-project/src/components/ReportModal/ReportModal.module.css, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/MyCourse/MyCourseWrite/MyCourseWrite.jsx, OMO-project/src/pages/login/Login.module.css
- 신고하기 아이콘 누르면 모달창 열리게 하기 
- 나만의 코스 찾기 버튼 누르면 모달창 열리게 하기
- 나만의 코스 찾기 버튼 공통 컴포넌트 세팅 
- 일부 디자인 수정
=> [Fe] 모달창 열기 기능 구현 및 공통 컴포넌트 세팅

src/main/java/com/OmObe/OmO/Board/controller/BoardController.java, src/main/java/com/OmObe/OmO/Board/service/BoardService.java, src/main/java/com/OmObe/OmO/advice/GlobalExceptionAdvice.java, src/main/java/com/OmObe/OmO/member/service/MemberService.java
- 게시글 작성 로직에 토큰 관련 로직 추가
- 좋아요 로직에 토큰 관련 로직 추가
=> [BE] 게시판, 좋아요 기능에 토큰 검증 로직 추가

build.gradle, src/main/java/com/OmObe/OmO/local/controller/LocalController.java
- 카카오 주소 검색 API를 통해 주소 검색 기능 구현
=> [BE] 주소 검색 구현

src/main/java/com/OmObe/OmO/weather/controller/WeatherController.java
=> [BE] 날씨 api 적용

OMO-project/src/components/ListSearch/ListSearch.jsx, OMO-project/src/pages/MyCourse/MyCourseMyVersionEdit/MyCourseMyVersionEdit.module.css, OMO-project/src/pages/list/List.jsx, OMO-project/src/pages/list/List.module.css
=> [Fe] 리스트 페이지 검색결과없음 기능 구현

.gitignore, application.yml, build.gradle, src/main/java/com/OmObe/OmO/Board/repository/BoardRepository.java, src/main/java/com/OmObe/OmO/Board/service/BoardService.java, src/main/java/com/OmObe/OmO/Comment/controller/CommentController.java, src/main/java/com/OmObe/OmO/Comment/entity/Comment.java, src/main/java/com/OmObe/OmO/Comment/repository/CommentRepository.java, src/main/java/com/OmObe/OmO/Comment/service/CommentService.java, src/main/java/com/OmObe/OmO/Place/controller/PlaceController.java, src/main/java/com/OmObe/OmO/Place/entity/Place.java, src/main/java/com/OmObe/OmO/Place/entity/PlaceLike.java, src/main/java/com/OmObe/OmO/Place/entity/PlaceRecommend.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceLikeRepository.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceRecommendRepository.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceRepository.java, src/main/java/com/OmObe/OmO/Place/service/PlaceService.java, src/main/java/com/OmObe/OmO/Review/dto/ReviewDto.java, src/main/java/com/OmObe/OmO/Review/entity/Review.java, src/main/java/com/OmObe/OmO/Review/mapper/ReviewMapper.java, src/main/java/com/OmObe/OmO/Review/repository/ReviewRepository.java, src/main/java/com/OmObe/OmO/util/PairJ.java
=> 장소 api 추가 완료

.gitignore, build.gradle, src/main/java/com/OmObe/OmO/Board/repository/BoardRepository.java, src/main/java/com/OmObe/OmO/Board/service/BoardService.java, src/main/java/com/OmObe/OmO/Comment/controller/CommentController.java, src/main/java/com/OmObe/OmO/Comment/entity/Comment.java, src/main/java/com/OmObe/OmO/Comment/repository/CommentRepository.java, src/main/java/com/OmObe/OmO/Comment/service/CommentService.java, src/main/java/com/OmObe/OmO/Place/controller/PlaceController.java, src/main/java/com/OmObe/OmO/Place/entity/Place.java, src/main/java/com/OmObe/OmO/Place/entity/PlaceLike.java, src/main/java/com/OmObe/OmO/Place/entity/PlaceRecommend.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceLikeRepository.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceRecommendRepository.java, src/main/java/com/OmObe/OmO/Place/repository/PlaceRepository.java, src/main/java/com/OmObe/OmO/Place/service/PlaceService.java, src/main/java/com/OmObe/OmO/Review/dto/ReviewDto.java, src/main/java/com/OmObe/OmO/Review/entity/Review.java, src/main/java/com/OmObe/OmO/Review/mapper/ReviewMapper.java, src/main/java/com/OmObe/OmO/Review/repository/ReviewRepository.java, src/main/java/com/OmObe/OmO/util/PairJ.java
후에 한꺼번에 application.yml 삭제하는 걸로 (BFG 이용)
=> 한꺼번에 삭제하기 위해 다시 복구

OMO-project/src/App.jsx, OMO-project/src/components/CategoryBox/CategoryBox.module.css, OMO-project/src/components/CommunityMyCourseList/CommunityMyCourseList.jsx, OMO-project/src/components/MyCourse/Button/ComeBackList/ComeBackList.module.css, OMO-project/src/components/MyCourse/MyCourseFindBox/MyCourseFindBox.jsx, OMO-project/src/components/MyCourse/MyCourseFindRecentModal/MyCourseFindRecentModal.jsx, OMO-project/src/components/MyCourse/MyCourseFindSearchModal/MyCourseFindSearchModal.jsx, OMO-project/src/components/MyCourse/MyCourseItemListBox/MyCourseItemListBox.jsx, OMO-project/src/components/MyCourseDetailBox/MyCourseDetailBox.jsx, OMO-project/src/components/MyCourseDetailBox/MyCourseDetailBox.module.css, OMO-project/src/components/MyCourseEditor/MyCourseEditor.jsx, OMO-project/src/components/MyCourseOthersDataBox/MyCourseOthersDataBox.jsx, OMO-project/src/components/MyCourseOthersDataBox/MyCourseOthersDataBox.module.css, OMO-project/src/components/MyWrotePost/MyWrotePost.jsx, OMO-project/src/components/MypageWroteMain/MypageWroteMain.jsx, OMO-project/src/const/communityMyCourse.js, OMO-project/src/pages/MyCourse/MyCourseDetail/MyCourseDetail.jsx, OMO-project/src/pages/MyCourse/MyCourseDetail/MyCourseDetail.module.css, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx, OMO-project/src/pages/MyCourse/MyCourseOthersVersion/MyCourseOthersVersion.jsx, OMO-project/src/pages/MyCourse/MyCourseOthersVersion/MyCourseOthersVersion.module.css, OMO-project/src/pages/Mypage/MyWrote/MyWrote.jsx
- 나만의 코스 다른 사람 ver 상세 페이지 마크업 
- 나만의 코스 다른사람 ver 상세페이지와 리스트페이지  router 설정
- 나만의 코스 content를 상세페이지로 렌더링
- 나만의 코스 달력에서 해당 월에 게시글 없을 시 메시지 표시
- 나만의 코스 최근 본 목록, 검색으로 찾기 추가 시 뜨는 에러 해결 
- 나만의 코스 글쓰기에서 배열 1번 부터 들어가는 문제 해결 (0번 부터 들어가게 하기)
- 나만의 코스에서 배열의 마지막 요소에는 화살표 이미지 안뜨게 하기
- 나만의 코스 리스트 dummyData 삭제
=> [Fe] 나만의 코스 상세페이지 기능 구현

OMO-project/src/components/CommunityInquiryBox/CommunityInquiryBox.module.css, OMO-project/src/components/CommunityPostItem/CommunityPostItem.module.css, OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.module.css, OMO-project/src/components/MyCourse/MyCourseItem/MyCourseItem.module.css, OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.jsx, OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.module.css, OMO-project/src/components/MypageListBox/MypageListBox.module.css, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.module.css, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.module.css, OMO-project/src/components/NoticeItems/NoticeItems.module.css, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.module.css, OMO-project/src/pages/signup/Signup.module.css
- 나만의 코스 필터 기능 삭제 
- 웹 전반적인 스타일 수정
=> [Fe] 나만의 코스 필터 기능 삭제 및 웹 전반적인 스타일 수정

src/main/java/com/OmObe/OmO/Place/service/PlaceService.java
=> Place add on

src/main/java/com/OmObe/OmO/Place/service/PlaceService.java, src/main/java/com/OmObe/OmO/Review/controller/ReviewController.java, src/main/java/com/OmObe/OmO/Review/service/ReviewService.java
=> Place list add on

src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
- setAllowedCredentials(true)설정
- 요청 시 허용 헤더 추가
- 응답 헤더 추가
=> [BE] CORS 설정 추가(헤더, Credentials)Be

OMO-project/.eslintrc.cjs, OMO-project/package-lock.json, OMO-project/package.json, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/utils/Time/simpleDateTimeFormat.js
=> [Develop] 상세페이지 axios로 서버 데이터 받아오기

src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
- setAllowedOriginPatterns() 추가
=> [BE] : CORS 설정 변경(setAllowedOriginPatterns)

OMO-project/src/App.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/ListBox/ListBox.jsx, OMO-project/src/components/ListBox/ListBox.module.css, OMO-project/src/components/Search/Search.jsx, OMO-project/src/components/Weather/Weather.module.css, OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx, OMO-project/src/pages/list/List.jsx, OMO-project/src/pages/main/Main.jsx, OMO-project/src/pages/main/Main.module.css, OMO-project/src/pages/sub/ThemeCafe/ThemeCafe.jsx, OMO-project/src/pages/sub/eating/Eating.jsx, OMO-project/src/pages/sub/playing/Playing.jsx, OMO-project/src/pages/sub/watching/Watching.jsx
- 메인페이지 검색창 수정
- 리스트페이지 필터 기능 수정
- 리스트페이지에서 상세페이지 통신 연결
=> [Develop] 메인페이지 검색창, 리스트페이지 및 상세페이지 통신 연결

src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
- 프론트엔드 로그인 기능 테스트 위해 임시로 origin 허용 범위를 전체로 수정(추후 origin범위 수정 필요)
=> [BE] : origin 허용 범위 수정(임시)

src/main/java/com/OmObe/OmO/auth/config/WebConfig.java, src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java, src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
- oauth 로그인 시 토큰을 쿼리 파라미터로 전달
- oauth 로그인 성공 후 토큰을 응답 헤더에 저장하는 컨트롤러 설정
=> [BE] oauth 로그인 후 토큰 처리 수정

src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java, src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
- oauth 로그인 인증 성공 후 사용자의 최초 로그인 여부를 "true"/"false"(String 타입)로 리턴하여 쿼리 파라미터로 전달
=> [BE] oauth 로그인 시 쿼리 파라미터로 최초 로그인 여부 전달

src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
- oauth 로그인 후 리다이렉트되는 경로에 쿼리 파라미터 전달하도록 수정
=> [BE] oauth 로그인 후 쿼리 파라미터 전달 코드 수정

OMO-project/src/const/themeCafe.js, OMO-project/src/pages/LoginLoading/LoginLoading.jsx, OMO-project/src/pages/login/Login.jsx
- 로그인 페이지 axios에서 href로 변경
- 카테고리 동물-> 동물원으로 변경
=> [Develop] 로그인 href로 수정 및 카테고리 동물원으로 변경

src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
- oauth 로그인 후 리다이렉트 경로 수정(/LoginLoading)
=> [BE] oauth 로그인 후 리다이렉트 경로 수정

src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java, src/main/java/com/OmObe/OmO/auth/config/WebConfig.java, src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
- 프론트 엔드 페이지 uri에 대한 cors 허용
- oauth 로그인 후 프론트 엔드 페이지로 리다이렉트
=> [BE] CorsConfiguration 수정

OMO-project/.eslintrc.cjs, OMO-project/src/components/Calender/Calendar.jsx, OMO-project/src/components/Radio/Radio.jsx, OMO-project/src/pages/signup/Signup.jsx, OMO-project/src/pages/signup/Signup.module.css
=> [Develop] 회원가입 유효성 검사

src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
- oauth 로그인 후 쿼리파라미터에 memberId 추가
=> [BE] oauth 로그인 후 쿼리파라미터에 memberId 추가

OMO-project/package-lock.json, OMO-project/package.json, OMO-project/src/App.jsx, OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/CommunityWorryPostList/CommunityWorryPostList.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/Header/Header.jsx, OMO-project/src/components/Header/Header.module.css, OMO-project/src/components/KaKaoMap/KaKaoMap.jsx, OMO-project/src/components/ListBox/ListBox.jsx, OMO-project/src/components/Mypage/Mypage.jsx, OMO-project/src/components/MypageListBox/MypageListBox.jsx, OMO-project/src/components/MypageListBox/MypageListBox.module.css, OMO-project/src/main.jsx, OMO-project/src/pages/Community/InquiryBoardFrequent/InquiryBoardFrequent.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx, OMO-project/src/pages/LoginLoading/LoginLoading.jsx, OMO-project/src/pages/Mypage/Interest/Interest.jsx, OMO-project/src/pages/Mypage/Interest/Interest.module.css, OMO-project/src/pages/Mypage/MyInfo/MyInfo.jsx, OMO-project/src/pages/Mypage/Recent/Recent.jsx, OMO-project/src/pages/Mypage/Recommend/Recommend.jsx, OMO-project/src/pages/list/List.jsx, OMO-project/src/pages/notice/Notice.jsx
<상세페이지>
- 추천 PUT, GET
- 관심 PUT, GET
<커뮤니티>
- 조회수 삭제
- 고민게시판 좋아요 GET, PUT
- 문의게시판 자주하는 질문 GET
<로그아웃>
- 통신 완료
<마이페이지>
- 최근본장소 로컬스토리지 
- 추천한 장소 
- 관심 목록
=> [Fe] 상세페이지, 커뮤니티, 마이페이지, 로그아웃 통신 

OMO-project/src/App.jsx, OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/ListBox/ListBox.jsx, OMO-project/src/components/MyWrotePost/MyWrotePost.jsx, OMO-project/src/components/Mypage/Mypage.jsx, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx, OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.module.css, OMO-project/src/components/MypageWroteMain/MypageWroteMain.jsx, OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx, OMO-project/src/pages/LoginLoading/LoginLoading.jsx, OMO-project/src/pages/Mypage/Interest/Interest.jsx, OMO-project/src/pages/Mypage/MyWrote/MyWrote.jsx, OMO-project/src/pages/Mypage/Recommend/Recommend.jsx
- 마이페이지 프로필 변경버튼 추가 및 MBTI 수정 PATCH 통신 완료
- 리뷰 MERGE
=> [Develop] 마이페이지 통신

OMO-project/src/App.jsx, OMO-project/src/assets/context/ProfileImageContext.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/Mypage/Mypage.jsx, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.module.css, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.module.css, OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx, OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.module.css, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.module.css, OMO-project/src/pages/Mypage/MyInfo/MyInfo.jsx, OMO-project/src/pages/signup/Signup.jsx
- 각각 변경하기 window.confirm 버튼에서 취소 버튼 누르면 초기화
- 프로필 이미지 변경 통신 완료
- 프로필 닉네임 중복 확인 기능 추가
- vercel.json 추가 (배포 url로 로그인 시 404 뜨면서 안되는 문제 해결)
=> [Develop] 프로필 변경 통신 완료 및 vercel.json 추가

OMO-project/src/components/CommunityMyCourseList/CommunityMyCourseList.jsx, OMO-project/src/components/CommunityMyCourseList/CommunityMyCourseList.module.css, OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/CommunityPostItem/CommunityPostItem.module.css, OMO-project/src/components/CommunityWorryPostList/CommunityWorryPostList.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/ListSearch/ListSearch.jsx, OMO-project/src/components/MyCourse/MyCourseAfter/MyCourseAfter.jsx, OMO-project/src/components/MyCourse/MyCourseCalendar/MyCourseCalendar.jsx, OMO-project/src/components/MyCourse/MyCourseFindBox/MyCourseFindBox.jsx, OMO-project/src/components/MyCourse/MyCourseItem/MyCourseItem.jsx, OMO-project/src/components/MyCourse/MyCourseItem/MyCourseItem.module.css, OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.jsx, OMO-project/src/components/MyCourseEditor/MyCourseEditor.jsx, OMO-project/src/components/MyCourseEditor/MyCourseEditor.module.css, OMO-project/src/const/communityPageFilter.js, OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx, OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.jsx, OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.module.css, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/MyCourse/MyCourseDetail/MyCourseDetail.jsx, OMO-project/src/pages/Mypage/MyInfo/MyInfo.jsx, OMO-project/src/pages/Mypage/MyInfo/MyInfo.module.css
- 커뮤니티 나만의 코스, 나만의 코스 리스트에 myLiked 데이터 추가 
- 나만의 코스 상세페이지에 myLiked 데이터 추가
- 내정보 항목에 Link 추가
- 나만의 코스 상세페이지에 날짜만 보이던 것을 시간까지 보이게 수정
- 나만의 코스 편집 페이지에서 코스 추가하면 달력에 실제 현재시간 뜨게 수정
- 나만의 코스 편집 시 삭제 버튼과 데이터 일치하게끔 구현
- 나만의 코스 편집에서 input 스타일 수정
- 커뮤니티 고민/자유 게시판에 필터링 넣으면 댓글/좋아요 먹통되는 것 해결
- 커뮤니티에서 댓글에 프로필 사진 보이게 추가
- 커뮤니티에서 댓글수 부분에 cursor:pointer 추가
=> [Develop] 커뮤니티, 나만의 코스, 내정보 수정

OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/MyCourse/Button/Share/Share.jsx, OMO-project/src/pages/MyCourse/MyCourseDetail/MyCourseDetail.jsx, OMO-project/src/pages/Mypage/Recent/Recent.jsx
- 나만의 코스 커뮤니티에 공유 기능 추가
- 최근 본 목록 POST 통신으로 변경
=> [Develop] 나만의 코스 커뮤니티에 공유 기능 추가, 최근 본 목록 POST 통신으로 변경

OMO-project/src/components/MyCourse/MyCourseFindInterestModal/MyCourseFindInterestModal.jsx, OMO-project/src/components/MyCourse/MyCourseFindRecentModal/MyCourseFindRecentModal.jsx, OMO-project/src/components/MyCourse/MyCourseFindRecommendModal/MyCourseFindRecommendModal.jsx
=> [fix] 나만의 코스 검색 코드 되돌림

OMO-project/src/components/MyCourse/MyCourseFindInterestModal/MyCourseFindInterestModal.jsx, OMO-project/src/components/MyCourse/MyCourseFindRecentModal/MyCourseFindRecentModal.jsx, OMO-project/src/components/MyCourse/MyCourseFindRecommendModal/MyCourseFindRecommendModal.jsx, OMO-project/src/components/MyCourse/MyCourseItemListBox/MyCourseItemListBox.jsx, OMO-project/src/pages/list/List.jsx, OMO-project/src/pages/main/Main.jsx
- 나만의코스 최근본목록 post 통신 추가
- 검색 위치 로컬스토리지 저장
=> [Develop] 나만의코스 최근본목록 post 통신 추가, 검색 위치 로컬스토리지 저장

OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.module.css, OMO-project/src/components/TokenExtension/TokenExtension.jsx
- 토큰 자동 갱신 및 UI에서 제거
- mbti 통계 스타일 수정
=> [Develop] 토큰 자동 갱신 및 UI에서 제거 및 기타 스타일 수정

OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx, OMO-project/src/main.jsx, OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx, OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx, OMO-project/src/pages/LoginLoading/LoginLoading.jsx, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx, OMO-project/src/pages/MyCourse/MyCourseNewWrite/MyCourseNewWrite.jsx, OMO-project/src/pages/signup/Signup.jsx
마이페이지 map오류 해결 (관심/추천/최근) (=나만의 코스 찾기도)
로그인 안하거나, 회원정보 입력 안할 경우(GUEST) 처리
(1)사용자가 토큰이 있고 memberRole이 GUEST면 회원정보 입력(/Signup)으로 이동  
(2)사용자가 토큰이 없으면 로그인 페이지 (/Login)으로 이동  
(1),(2)도 아닌 경우 (사용자가 토큰이 있고 memberRole이 USER인 경우는 원래대로 통신 진행)
- 커뮤니티 댓글 (완료)
- 커뮤니티 글쓰기 (완료)
- 코스 작성 (완료)
- 장소 좋아요, 추천, 리뷰 (완료)
회원정보 입력하면 로컬스토리지에서 memberRole을 GUEST에서 USER로 바뀌게 하기
=> [Develop] GUEST, USER, 로그아웃 유저 분기 나눠서 해결, 마이페이지 오류 해결 

OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/MyCourseEditor/MyCourseEditor.jsx, OMO-project/src/components/Mypage/Mypage.jsx, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx, OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx, OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx, OMO-project/src/components/WritePost/WriteFreeBoard/WriteFreeBoard.jsx, OMO-project/src/components/WritePost/WriteQnABoard/WriteQnABoard.jsx, OMO-project/src/components/WritePost/WriteWorryBoard/WriteWorryBoard.jsx, OMO-project/src/main.jsx, OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx, OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/LoginLoading/LoginLoading.jsx, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx, OMO-project/src/pages/MyCourse/MyCourseNewWrite/MyCourseNewWrite.jsx, OMO-project/src/pages/Mypage/MyInfo/MyInfo.jsx, OMO-project/src/pages/signup/Signup.jsx
- 사용자가 GUEST일 경우 로컬스토리지 안쓰고 403에러로 리다이렉션 처리함
- 기존에 memberId를 받는 요청을 로컬스토리지로 memberId를 받지 않고 헤더에 들어오는 토큰으로만 처리하도록 수정
- 회원가입 title을 "회원 정보 추가 입력"으로 수정
=> [Develop] GUEST, memberId 관련 수정

OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/MyCourse/MyCourseDataBox/MyCourseDataBox.jsx, OMO-project/src/components/MyCourseDetailBox/MyCourseDetailBox.jsx, OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx, OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx
- 자유/고민게시판 새로고침 시에도 좋아요 클릭 유지되게 수정
- QnA게시판 로그인 유무 따라 통신 다르게 하기
=> [Develop] 커뮤니티 로그인 유무에 따라 통신 다르게 하기

OMO-project/src/components/CommunityPostItem/CommunityPostItem.jsx, OMO-project/src/components/CommunityPostItem/CommunityPostItem.module.css, OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx, OMO-project/src/components/MyCourseEditor/MyCourseEditor.jsx, OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx, OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx, OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx, OMO-project/src/components/TokenExtension/TokenExtension.jsx, OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx, OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx, OMO-project/src/pages/MyCourse/MyCourseDetail/MyCourseDetail.jsx, OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx
- 커뮤니티 나만의 코스 좋아요 기능에서 GUEST일 경우 403에러에 따라 리디렉션 하는 것으로 변경
- 리팩토링
=> [Develop] 커뮤니티 나만의 코스 좋아요 기능에서 GUEST일 경우 403에러에 따라 리디렉션 하는 것으로 변경

OMO-project/vite.config.js
=> [feat] proxy 설정
